import * as turf from '@turf/turf';
import type { Feature, LineString, Point } from 'geojson';
import type { CableProperties, MarkerProperties, MarkerFeatureCollection } from '../types';

/**
 * MarkerGenerator Service
 * 
 * Generates marker points along cable routes at specified intervals using Turf.js
 * for geometric calculations.
 * 
 * Requirements: 3.1, 3.4, 3.5, 8.5
 */
export class MarkerGenerator {
  /**
   * Generate marker points along a cable route at specified intervals
   * 
   * @param lineString - Cable route as GeoJSON LineString Feature
   * @param intervalMeters - Distance between markers in meters (default: 30)
   * @returns FeatureCollection of marker points with properties
   * @throws Error if LineString is invalid or Turf.js calculations fail
   */
  generateMarkers(
    lineString: Feature<LineString, CableProperties>,
    intervalMeters: number = 30
  ): MarkerFeatureCollection {
    try {
      // Validate input - Requirement 8.5
      if (!lineString || !lineString.geometry || lineString.geometry.type !== 'LineString') {
        throw new Error('Invalid LineString geometry');
      }

      if (!lineString.geometry.coordinates || lineString.geometry.coordinates.length < 2) {
        throw new Error('LineString must have at least 2 coordinates');
      }

      if (intervalMeters <= 0) {
        throw new Error('Interval must be greater than 0');
      }

      // Handle Turf.js calculation errors - Requirement 8.5
      const totalDistance = this.calculateTotalDistance(lineString);
      const markers: Feature<Point, MarkerProperties>[] = [];

      // Edge case: routes shorter than interval distance - Requirement 3.4
      // Place markers at start and end only
      if (totalDistance < intervalMeters) {
        const startPoint = this.createMarkerAtDistance(lineString, 0);
        const endPoint = this.createMarkerAtDistance(lineString, totalDistance);
        
        if (startPoint) markers.push(startPoint);
        if (endPoint && totalDistance > 0) markers.push(endPoint);
        
        return turf.featureCollection(markers);
      }

      // Generate markers at regular intervals
      for (let distance = 0; distance <= totalDistance; distance += intervalMeters) {
        const marker = this.createMarkerAtDistance(lineString, distance);
        if (marker) {
          markers.push(marker);
        }
      }

      // Ensure we have a marker at the end if not already placed
      const lastMarkerDistance = markers.length > 0 
        ? markers[markers.length - 1].properties.distanceFromStart 
        : -1;
      
      if (Math.abs(lastMarkerDistance - totalDistance) > 0.1) {
        const endMarker = this.createMarkerAtDistance(lineString, totalDistance);
        if (endMarker) {
          markers.push(endMarker);
        }
      }

      return turf.featureCollection(markers);
    } catch (error) {
      // Log error and re-throw with context - Requirement 8.5
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      console.error(`MarkerGenerator error for cable ${lineString.properties?.id}:`, errorMsg);
      throw new Error(`Failed to generate markers: ${errorMsg}`);
    }
  }

  /**
   * Calculate the total distance of a cable route
   * 
   * @param lineString - Cable route as GeoJSON LineString Feature
   * @returns Total distance in meters
   * @throws Error if Turf.js calculation fails
   */
  calculateTotalDistance(lineString: Feature<LineString, CableProperties>): number {
    try {
      // Handle Turf.js calculation errors - Requirement 8.5
      return turf.length(lineString, { units: 'meters' });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      console.error('Error calculating distance:', errorMsg);
      throw new Error(`Failed to calculate distance: ${errorMsg}`);
    }
  }

  /**
   * Create a marker point at a specific distance along the route
   * 
   * @param lineString - Cable route as GeoJSON LineString Feature
   * @param distance - Distance from start in meters
   * @returns Marker feature with properties, or null if creation fails
   */
  private createMarkerAtDistance(
    lineString: Feature<LineString, CableProperties>,
    distance: number
  ): Feature<Point, MarkerProperties> | null {
    try {
      // Handle Turf.js calculation errors - Requirement 8.5
      const point = turf.along(lineString, distance, { units: 'meters' });
      
      if (!point || !point.geometry || !point.geometry.coordinates) {
        throw new Error('Invalid point generated by Turf.js');
      }

      const markerProperties: MarkerProperties = {
        cableId: lineString.properties.id,
        soilType: lineString.properties.soilType,
        depth: lineString.properties.depth,
        distanceFromStart: distance,
        coordinates: point.geometry.coordinates as [number, number]
      };

      return {
        type: 'Feature',
        geometry: point.geometry,
        properties: markerProperties
      };
    } catch (error) {
      // Log error but return null to allow graceful degradation - Requirement 8.5
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      console.error(`Error creating marker at distance ${distance}:`, errorMsg);
      return null;
    }
  }
}

// Export singleton instance
export const markerGenerator = new MarkerGenerator();
